export SHELL = /bin/sh
export CFLAGS=-Wall -O3 -DVGM_USE_G7221 -I../ext_includes
export LDFLAGS=-lm -L../src -L../ext_libs -lvgmstream -lvorbis -lmpg123-0 -lg7221_decode
export CC=i586-mingw32msvc-gcc
export AR=i586-mingw32msvc-ar
export STRIP=i586-mingw32msvc-strip

.PHONY: libvgmstream.a libvorbis.a libmpg123-0.a libg7221_decode.a

test.exe: libvgmstream.a libvorbis.a libmpg123-0.a libg7221_decode.a
	$(CC) $(CFLAGS) "-DVERSION=\"`../version.sh`\"" test.c $(LDFLAGS) -o test.exe
	$(STRIP) test.exe

libvgmstream.a:
	$(MAKE) -C ../src $@

libvorbis.a:
	$(MAKE) -C ../ext_libs -f Makefile.mingw $@

libmpg123-0.a:
	$(MAKE) -C ../ext_libs -f Makefile.mingw $@

libg7221_decode.a:
	$(MAKE) -C ../ext_libs -f Makefile.mingw $@

clean:
	rm -f test.exe
