#!/bin/sh
# vgmstream autotools script - reverses the actions of bootstrap

rm -rf configure AUTHORS compile depcomp ChangeLog config.guess ltmain.sh README config.sub autom4te.cache Makefile.autotools.in INSTALL missing NEWS aclocal.m4 install-sh
rm -rf audacious/config.h.in audacious/main.loT audacious/Makefile.autotools.in src/Makefile.autotools.in
rm -rf src/coding/Makefile.autotools.in src/meta/Makefile.autotools.in src/layout/Makefile.autotools.in cli/Makefile.autotools.in
rm -rf config.log config.status libtool Makefile.autotools

find . -type f -name "*.lo" -exec rm -f {} \;
find . -type f -name "*.la" -exec rm -f {} \;
find . -type d -name ".deps" -exec rm -r {} +;
find . -type d -name ".libs" -exec rm -r {} +;
find . -type f -name "*.Plo" -exec rm -f {} \;
find . -type f -name ".dirstamp" -exec rm -f {} \;
find . -type f -name "stamp-h1" -exec rm -f {} \;

