/* Static/fallback version.
 * Version is autogenerated from Git (passed via compiler args, or updated with scripts), but this file is
 * for Git-less builds (not installed or downloaded master) and builds that don't do the above should still work. */
#define VGMSTREAM_VERSION "unknown"
