#!/bin/sh

# make current git version (overwrites version_auto.h)
VERSION_NAME=VGMSTREAM_VERSION
VERSION_FILE=version_auto.h


# test if git exists
if ! command -v git > /dev/null ; then
    VERSION=""
else
    VERSION=$(git describe --always 2>&1 | tr : _ )
fi


# ignore git stderr "fatal:*" or blank
if  [[ $VERSION != fatal* ]] && [ ! -z "$VERSION" ] ; then
    echo "#define $VERSION_NAME \"$VERSION\" /* autogenerated */" > $VERSION_FILE
else
    echo "Git version not found, can't autogenerate version_auto.h"
fi;
