#define IDD_CONFIG                      101
#define IDC_LOOP_COUNT                  1000
#define IDC_FADE_TIME                   1001
#define IDC_FADE_DELAY                  1002
#define IDC_LOOP_NORMALLY               1003
#define IDC_LOOP_FOREVER                1004
#define IDC_IGNORE_LOOP                 1005
#define IDC_THREAD_PRIORITY_SLIDER      1006
#define IDC_THREAD_PRIORITY_TEXT        1007
#define IDC_DEFAULT_BUTTON              1008
#define IDC_DISABLE_SUBSONGS            1009
#define IDC_DOWNMIX_CHANNELS            1011
#define IDC_TAGFILE_DISABLE             1012
#define IDC_GAIN_TYPE                   1013
#define IDC_CLIP_TYPE                   1014
#define IDC_EXTS_UNKNOWN_ON             1015
#define IDC_EXTS_COMMON_ON              1016
#define IDC_FORCE_TITLE                 1017
#define IDC_LOG_BUTTON                  1018
