name: Windows build

on:
  push:
    branches: [ master, main ]
    tags: [ 'r*' ]
    paths-ignore: ['doc/**', '**.md', 'COPYING', '.gitignore', 'cli/tools/**']
  pull_request:
    paths-ignore: ['doc/**', '**.md', 'COPYING', '.gitignore', 'cli/tools/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Visual Studio
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v6
        # needs history + tags for auto-versioning
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Initialize build environment
        shell: cmd
        run: powershell -ExecutionPolicy Bypass -NoProfile -File .\msvc-build.ps1 Init

      - name: Build
        shell: cmd
        run: powershell -ExecutionPolicy Bypass -NoProfile -File .\msvc-build.ps1 Build

      - name: Prepare files for packaging
        shell: powershell
        run: powershell -ExecutionPolicy Bypass -NoProfile -File .\msvc-build.ps1 PackageArtifacts

      # upload to "actions" tab artifacts (can only make a single .zip from a dir's files)
      - name: Upload foobar2000 component
        uses: actions/upload-artifact@v7
        with:
          name: foo_input_vgmstream.fb2k-component
          path: ${{github.workspace}}\bin\artifacts\foobar2000

      - name: Upload CLI tools 32-bit
        uses: actions/upload-artifact@v7
        with:
          name: vgmstream-win
          path: ${{github.workspace}}\bin\artifacts\cli-x32

      - name: Upload CLI tools 64-bit
        uses: actions/upload-artifact@v7
        with:
          name: vgmstream-win64
          path: ${{github.workspace}}\bin\artifacts\cli-x64

      - name: Upload debug symbols
        uses: actions/upload-artifact@v7
        with:
          name: debug-symbols-pdb
          path: ${{github.workspace}}\bin\artifacts\pdb

      # uploads current assets to vgmstream-releases (token only works on merges)
      - name: Upload artifacts to vgmstream-releases
        if: github.event_name != 'pull_request'
        shell: cmd
        working-directory: ${{github.workspace}}
        env:
          UPLOADER_GITHUB_TOKEN: ${{ secrets.UPLOADER_GITHUB_TOKEN }}
        run: |
          python .github\uploader.py bin\vgmstream-win.zip bin\vgmstream-win64.zip bin\foo_input_vgmstream.fb2k-component
          python .github\uploader.py --changelog
